[package]
name = "csv-diff"
version = "0.1.0"
authors = ["Jan Riemer <janriemer@tutanota.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rayon = "1.5"
twox-hash = "1.6.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3"
utils = { path = "benches/utils" }

[[bench]]
name = "bench_csv_diff"
harness = false