[package]
name = "utils"
version = "0.1.0"
authors = ["Jan Riemer <janriemer@tutanota.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = "2.2"
rand = "0.7.3"